In [1]:
#required libraries
import numpy as np 
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0") #making a ne env of frozen lake game

[2022-06-14 12:51:57,215] Making new env: FrozenLake-v0
/home/bethoveen/.local/lib/python3.10/site-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [3]:
print(env.action_space.n) #prints how many Actions from each statethere is 

4


In [4]:
#now we will Create our Qtable StatesxActions {0}
#since initially all our Q values are zeros
Q_table = np.zeros((env.observation_space.n,env.action_space.n))
print (Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#setting up our parameters we discussed earlier

episodes = 10000  #this refers to the number of episodes we want or agent to play
Max_steps = 50 #this refers to the Maxnumber of steps at each episode , if exceeded the episode will end immeditely  
learning_rate  = 0.1 # α : rate of updating Q value  
discount_rate  = 0.99 # 𝛾 : rate of decay of rewards
exploration_rate = 1 #ε : prob. of our agent exploring the environment instead of exploiting it
max_exploration_rate = 1
min_exploration_rate = 0.01
explortion_decay = 0.009
rewards_all_episodes = [] # we will use this to visulatize the rewards for each episode

***quick reminder of what we want to do in the algorithm***

1) at the beggining of each episdoe we need to reset the state to inital
2) now for each step in the episdoe we need to randomly select wether to explore or exploit according to a random value r realtive to the ε value (r<ε -> explore) (r>ε -> exploit)
3) take an acction with explor-exploit in-mind
4) updating our Q-table values
5) then set our state to the new state and add the reward to the total rewards of the episode
6) finally we would update ε using exploration decay rate 


In [6]:
# ****Q-Learning algorithm****
for episode in range(episodes):
    current_state = env.reset() #at the beggining of each episode we set state to initial state
    ep_done = False
    total_episode_reward = 0

    #steps code
    for step in range(Max_steps):
        #uncomment to see Agent playing
        clear_output(wait=True)
        env.render()
        time.sleep(0.1)
        
        #exploration vs epoitation
        r = random.uniform(0,1)
        if(r<exploration_rate):
            #explore action
            action  = env.action_space.sample()
        else:
            #exploit action
            action = np.argmax(Q_table[current_state,:])
        
        #taking the action    
        new_state, reward, ep_done,info  = env.step(action)
        
        #updating Q_table values
        Q_table[current_state,action] = (1-learning_rate) * Q_table[current_state,action] + learning_rate * (reward + discount_rate * (np.max(Q_table[new_state,:])))
        current_state = new_state
        total_episode_reward += reward
        
        #checking if the step made us end the game
        if ep_done == True:
            #print(reward)
            break; #then end the episode without taking any other steps
    
    #now updating the exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-explortion_decay * episode)
    rewards_all_episodes.append(total_episode_reward)

  (Left)
SFFF
FHFH
FFFH
HFFG


In [7]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


In [8]:
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
